version: "3.3"
services:
  web:
    build:
      context: ../../.
      dockerfile: ./docker/development/Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - AUTH_APP_ID=${AUTH_APP_ID}
      - AUTH_APP_SECRET=${AUTH_APP_SECRET}
    ports:
      - "3000:3000"
      - "1025:1025"
      - "1080:1080"
    volumes: 
      - ../../:/usr/src/app
    depends_on:
      - db
      - redis
  db:
    image: postgres
    restart: always
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"