version: "3.3"
services:
  web:
    build:
      context: ../../.
      dockerfile: ./docker/development/Dockerfile
    environment:
      - SECRET_KEY_BASE=c2e990232c98dced9b6a81b832b5fe8b5ac3d46501c73d860962622e3d73282bfc21443a93e7fac522a9db99204e8e224a08f92825f57aa0be7b305bd0ae7bc3
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"